const events = [
  {
    eventId: 1,
    eventName: 'The Bolshoi Theatre Opera',
    eventCity: 'Moscow',
    eventCityId: 1,
    eventTheme: 'Theatre',
    eventTime: '19:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 2,
    eventName: 'St Petersburg Philharmonic',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '18:00',
    eventThumbnailUrl: 'http://i.imgur.com/PSnvHng.jpg',
  },
  {
    eventId: 3,
    eventName: 'Museum of History of Tomsk Exhibition',
    eventCity: 'Tomsk',
    eventCityId: 3,
    eventTheme: 'Museum',
    eventTime: '18:00',
    eventThumbnailUrl: 'http://i.imgur.com/ta42OkB.jpg',
  },
  {
    eventId: 4,
    eventName: 'Christmas concert by «Tango Misterioso»',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '16:00',
    eventThumbnailUrl: 'http://i.imgur.com/A1rT3uw.jpg',
  },
  {
    eventId: 5,
    eventName: 'El Corazon concert',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '17:00',
    eventThumbnailUrl: 'http://i.imgur.com/8wb5GqE.jpg',
  },
  {
    eventId: 6,
    eventName: 'Anacondaz concert',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '21:00',
    eventThumbnailUrl: 'http://i.imgur.com/cNhFBpg.jpg',
  },
];

module.exports = {events};
