const events = [
  {
    eventId: 1,
    eventName: 'The Bolshoi Theatre Opera',
    eventCity: 'Moscow',
    eventCityId: 1,
    eventTheme: 'Theatre',
    eventTime: '19:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 2,
    eventName: 'St Petersburg Philharmonic',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '18:00',
    eventThumbnailUrl: 'http://i.imgur.com/PSnvHng.jpg',
  },
  {
    eventId: 3,
    eventName: 'Museum of History of Tomsk Exhibition',
    eventCity: 'Tomsk',
    eventCityId: 3,
    eventTheme: 'Museum',
    eventTime: '18:00',
    eventThumbnailUrl: 'http://i.imgur.com/ta42OkB.jpg',
  },
  {
    eventId: 4,
    eventName: 'Christmas concert by «Tango Misterioso»',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '16:00',
    eventThumbnailUrl: 'http://i.imgur.com/A1rT3uw.jpg',
  },
  {
    eventId: 5,
    eventName: 'El Corazon concert',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '17:00',
    eventThumbnailUrl: 'http://i.imgur.com/8wb5GqE.jpg',
  },
  {
    eventId: 6,
    eventName: 'Anacondaz concert',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '21:00',
    eventThumbnailUrl: 'http://i.imgur.com/cNhFBpg.jpg',
  },
  {
    eventId: 7,
    eventName: 'Test Saint Petersburg Concert',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '19:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 8,
    eventName: 'Test Saint Petersburg Concert 2',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Concert',
    eventTime: '22:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 9,
    eventName: 'Test Saint Petersburg Theatre 1',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Theatre',
    eventTime: '12:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 10,
    eventName: 'Test Saint Petersburg Theatre 2',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Theatre',
    eventTime: '16:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 11,
    eventName: 'Test Saint Petersburg Museum 1',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Museum',
    eventTime: '15:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 12,
    eventName: 'Test Saint Petersburg Museum 2',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Museum',
    eventTime: '18:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 13,
    eventName: 'Test Saint Petersburg Museum 3',
    eventCity: 'Saint Petersburg',
    eventCityId: 2,
    eventTheme: 'Museum',
    eventTime: '19:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 14,
    eventName: 'Test Moscow Museum 1',
    eventCity: 'Moscow',
    eventCityId: 1,
    eventTheme: 'Museum',
    eventTime: '16:00',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
  {
    eventId: 15,
    eventName: 'Test Moscow Concert 1',
    eventCity: 'Moscow',
    eventCityId: 1,
    eventTheme: 'Concert',
    eventTime: '15:55',
    eventThumbnailUrl: 'http://i.imgur.com/eZ3Bvkf.jpg',
  },
];

module.exports = {events};
