export const actionTypes = {
  REQUEST_EVENTS: 'REQUEST_EVENTS',
  REQUEST_EVENTS_SUCCSESS: 'REQUEST_EVENTS_SUCCSESS',
  REQUEST_EVENTS_FAIL: 'REQUEST_EVENTS_FAIL',

  SELECT_CITY: 'SELECT_CITY',
  SELECT_THEME: 'SELECT_THEME',
  SELECT_TIME: 'SELECT_TIME',
};
